### PR TITLE
TypeScript updates

### PR DESCRIPTION
**Pull request by GinoCanessa**
* Changed output to use ValueSet expansions instead of Resource Code definitions.
* Added 'resourceType: any' to Resource generic classes for better parsing.

### CODE REVIEW

**Comment by bkaney** [comment]
Hi @GinoCanessa great - I will try this out today and see how the tests pass.

**Comment by bkaney** [comment]
Hi @GinoCanessa  - I don't see the "Added `resourceType: any` in this patch?

**Comment by GinoCanessa** [comment]
@bkaney Odd that you couldn't see the files from my local machine that I forgot to push.  🤦 

Good catch on the array flags too - missed it when I added the new binding fields.  I've pushed that up as well, so both changes/fixes should be visible now.

**Comment by jmandel** [comment]
Is there a reason to prefer `resourceType: any` over `resourceType: string` in the base definition?

**Comment by bkaney** [comment]
> Is there a reason to prefer `resourceType: any` over `resourceType: string` in the base definition?

hmm, good point, I think `string` might be better here...

**Comment by bkaney** [comment]
@GinoCanessa hate to keep sending bad news :( but seeing problems (again with contained resources), for example: http://www.hl7.org/FHIR/activitydefinition-medicationorder-example.json.html

```
Conversion of type '{ resourceType: "ActivityDefinition"; id: string; contained: ({ resourceType: string; id: string; code: { coding: { system: string; code: string; }[]; text: string; }; form: { coding: { system: string; code: string; display: string; }[]; text: string; }; ingredient: { ...; }[]; } | { ...; })[]; ... 25 more ...; dyna...' to type 'ActivityDefinition' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'contained' are incompatible.
    Type '({ resourceType: string; id: string; code: { coding: { system: string; code: string; }[]; text: string; }; form: { coding: { system: string; code: string; display: string; }[]; text: string; }; ingredient: { itemReference: { ...; }; strength: { ...; }; }[]; } | { ...; })[]' is not comparable to type 'Resource[]'.
      Type '{ resourceType: string; id: string; code: { coding: { system: string; code: string; }[]; text: string; }; form: { coding: { system: string; code: string; display: string; }[]; text: string; }; ingredient: { itemReference: { ...; }; strength: { ...; }; }[]; } | { ...; }' is not comparable to type 'Resource'.
        Type '{ resourceType: string; id: string; code: { coding: { system: string; code: string; }[]; text: string; }; }' is not comparable to type 'Resource'.
          Object literal may only specify known properties, and '"code"' does not exist in type 'Resource'.ts(2352)
```

**Comment by GinoCanessa** [comment]
@bkaney, no worries!  I haven't been able to push on TS as much as some other languages, so it is great to have someone pushing on different areas.

The first issue is that `contained` is evil.  With that in mind, we have a few choices:
* change `DomainResource.contained` to `any`
* change `DomainResource.contained` to `Resource|<list of resource types>`

My concern with the latter is for evaluation of the interface.  While it's 'nicer', I don't believe the type checking is optimized for comparing ~140 interfaces ([Prefer base types over unions](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-base-types-over-unions)).

Thoughts?

**Comment by bkaney** [comment]
Right. I guess if we are optimizing for type checking performance, we should do option 1. But I am not sure how bad performance would be in option 2.

How's that for a complete non-answer ;) -- maybe for now we go with `any[]` preferring performance generally?

**Comment by GinoCanessa** [comment]
Well, in the interest of not guessing I implemented the second option so you can answer the question.  The most recent changes include changing `Resource.resourceType` to `string`, adding a new type, `FhirType` which is the union of the exported resources, and using that in places where the element type was `Resource` (very few).

I did not include `Resource` in the union, since an instantiated resource shouldn't be able to be one.  That said, it may be more convenient to include it for external use.  It's a one line of code change either way, so please let me know what's better.

If you want to test R4 using 'any' instead, the simplest is just to change the R4 TS file, it's only used in a few places (lines: 4504, 4532, 11443, and 21548).

**Comment by GinoCanessa** [comment]
Reported that the TS R4 output has been tested and is working well.

**Pull request merged**
