### PR TITLE
Bundle Generic Support in TS

### PR DESCRIPTION
**Pull request by GinoCanessa**
Forked from PR #66  in order to make corrections / changes and generate the TS files for review.

This version adds generic support to Bundle, Bundle.entry, and Bundle.entry.resource. It also fixes a few minor issues that creeped in during PR #66 .

In order to ensure there were no conflicts in the future, I added some hinting to the generic directives (e.g., instead of `T`, bundles have `BundleContentType`).  This way, if we move towards adding more generics in the future we don't have to rename all of these.

Thoughts? @jdkelly @ir4y @jmandel @bkaney

### CODE REVIEW

**Comment by bkaney** [comment]
IDK what this error means, or if it is a problem, but for all versions (2,3, and 4) I get this error when trying to package for DT:

image

Which in this case is where we define the resource binding:

image

---

@GinoCanessa  - There doesn't seem to me to be a circular reference, and I don't know if this a real problem? Or should I just add the minimum typescript 3.7 and call it good?

**Comment by bkaney** [comment]
I like being more explicit, instead of just `T`

**Comment by GinoCanessa** [comment]
I'm guessing it's a problem because `FhirResource` contains `Bundle`, which is now actually `Bundle<FhirResource>` by default.  I'm okay with adding a dependency on TS 3.7 (since I believe it was released late 2019).

If we are doing that, I should probably add the comment to the generated header as well, to prevent it from happening in the future.

**Comment by jdjkelly** [comment]
I agree with target > 3.7

**Comment by bkaney** [comment]
@GinoCanessa  - should this PR go into `dev`? Or should we merge `dev` to `main` first?

**Pull request merged**
